function [x_med, dx_med, ddx_med, x_des, dx_des, ddx_des] = get_cartesian_data(data,t_start, t_step, t_end)

x_med = [data.x_med(t_start:t_step: t_end),...
                data.y_med(t_start:t_step: t_end),...
                data.z_med(t_start:t_step: t_end)];

dx_med = [data.dx_med(t_start:t_step: t_end),...
                data.dy_med(t_start:t_step: t_end),...
                data.dz_med(t_start:t_step: t_end)];

ddx_med = [data.dx_med(t_start:t_step: t_end),...
                data.dy_med(t_start:t_step: t_end),...
                data.dz_med(t_start:t_step: t_end)];


x_des = [data.x_des(t_start:t_step: t_end),...
                data.y_des(t_start:t_step: t_end),...
                data.z_des(t_start:t_step: t_end)];

dx_des = [data.dx_des(t_start:t_step: t_end),...
                data.dy_des(t_start:t_step: t_end),...
                data.dz_des(t_start:t_step: t_end)];

ddx_des = [data.dx_des(t_start:t_step: t_end),...
                data.dy_des(t_start:t_step: t_end),...
                data.dz_des(t_start:t_step: t_end)];
end