function [q_med, dq_med, ddq_med, q_des, dq_des, ddq_des] = get_cartesian_data(data,t_start, t_step, t_end)

% angular position: desired
q_des= [    data.q1_des(t_start:t_step:t_end), ...
            data.q2_des(t_start:t_step:t_end), ...
            data.q3_des(t_start:t_step:t_end), ...
            data.q4_des(t_start:t_step:t_end), ...
            data.q5_des(t_start:t_step:t_end), ...
            data.q6_des(t_start:t_step:t_end)];  

% angular velocity: desired               
dq_des= [   data.dq1_des(t_start:t_step:t_end), ...
            data.dq2_des(t_start:t_step:t_end), ...
            data.dq3_des(t_start:t_step:t_end), ...
            data.dq4_des(t_start:t_step:t_end), ...
            data.dq5_des(t_start:t_step:t_end), ...
            data.dq6_des(t_start:t_step:t_end)];  

% angular acceleration: desired
ddq_des= [  data.ddq1_des(t_start:t_step:t_end), ...
            data.ddq2_des(t_start:t_step:t_end), ...
            data.ddq3_des(t_start:t_step:t_end), ...
            data.ddq4_des(t_start:t_step:t_end), ...
            data.ddq5_des(t_start:t_step:t_end), ...
            data.ddq6_des(t_start:t_step:t_end)];          

% angular position: measured
q_med= [    data.q1_med(t_start:t_step:t_end), ...
            data.q2_med(t_start:t_step:t_end), ...
            data.q3_med(t_start:t_step:t_end), ...
            data.q4_med(t_start:t_step:t_end), ...
            data.q5_med(t_start:t_step:t_end), ...
            data.q6_med(t_start:t_step:t_end)];  

% angular velocity: measured               
dq_med= [   data.dq1_med(t_start:t_step:t_end), ...
            data.dq2_med(t_start:t_step:t_end), ...
            data.dq3_med(t_start:t_step:t_end), ...
            data.dq4_med(t_start:t_step:t_end), ...
            data.dq5_med(t_start:t_step:t_end), ...
            data.dq6_med(t_start:t_step:t_end)];  

% angular acceleration: measured
ddq_med= [  data.ddq1_med(t_start:t_step:t_end), ...
            data.ddq2_med(t_start:t_step:t_end), ...
            data.ddq3_med(t_start:t_step:t_end), ...
            data.ddq4_med(t_start:t_step:t_end), ...
            data.ddq5_med(t_start:t_step:t_end), ...
            data.ddq6_med(t_start:t_step:t_end)];  

end